spring:
  application:
    name: todo-app-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    hibernate:
      ddl-auto: update
